# Generated by Django 5.2 on 2025-05-04 14:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='AttendanceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configapp.groupstudent')),
            ],
            options={
                'verbose_name': 'Davomat sessiyasi',
                'verbose_name_plural': 'Davomat sessiyalari',
                'unique_together': {('group', 'date')},
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('present', 'Keldi'), ('late', 'Kechikdi'), ('absent', 'Kelmagan')], default='absent', max_length=10)),
                ('student', models.ForeignKey(limit_choices_to={'is_student': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='configapp.attendancesession')),
            ],
            options={
                'verbose_name': 'O‘quvchi davomati',
                'verbose_name_plural': 'O‘quvchilar davomati',
                'unique_together': {('session', 'student')},
            },
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
