# Generated by Django 5.2 on 2025-05-04 16:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configapp', '0002_alter_user_is_staff_attendancesession_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendancesession',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='attendancesession',
            name='group',
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('present', 'Keldi'), ('late', 'Kechikdi'), ('absent', 'Kelmagan')], default='absent', max_length=10)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configapp.groupstudent')),
                ('student', models.ForeignKey(limit_choices_to={'is_student': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Davomat',
                'verbose_name_plural': 'Davomatlar',
                'unique_together': {('student', 'group', 'date')},
            },
        ),
        migrations.DeleteModel(
            name='AttendanceRecord',
        ),
        migrations.DeleteModel(
            name='AttendanceSession',
        ),
    ]
